version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=my-store,
      - POSTGRES_USER=bruno,
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data