services:
  postgres:
    image: postgres:13
    container_name: postgres-1
    environment:
      POSTGRES_USER: brunobalza
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my-store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bruno@example.com
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - "5050:80"
  mysql:
    image: mysql:9
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: my-store
      MYSQL_USER: brunobalza
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      PMA_HOST: mysql
    ports:
      - "8080:80"


volumes:
  pgdata:
  mysql:

